version: "3"
services:
  hub:
    image: selenium/hub:3.141.59
  chrome:
    image: selenium/node-chrome:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141.59
    shm_size: '1gb'   
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  Suite1:
    image: olatundji/selenium-docker-bdd
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
      - BROWSER=chrome
      - MODULE=./resources/suite.xml
    volumes:
      - ./output/suite-result:/usr/share/udemy/test-output